version: '3.8'
services:
  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: django-insecure-%!rdtu4fvk9@h@lr$$k#78pr1(wff78$$k6m%qv^k3i#x_qblywa
      DJANGO_DEBUG: true
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  postgres_data: